version: "3"
services:
  app1:
    image: springboot-docker-demo/demo1:latest
    #    build: ./demo1 # if using build approach, un-comment demo1 dir in .dockerignore file.
    container_name: sb-demo1
    networks:
      webnet:
        ipv4_address: 10.0.1.4
  app2:
    image: springboot-docker-demo/demo2:latest
    #    build: ./demo2 # if using build approach, un-comment demo2 dir in .dockerignore file.
    container_name: sb-demo2
    networks:
      webnet:
        ipv4_address: 10.0.1.3
  nginx:
    image: nginx:latest
    container_name: sb-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-data/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-data/html:/etc/nginx/nginx/html
      - ./nginx-data/log:/var/log/nginx
    networks:
      webnet:
        ipv4_address: 10.0.1.2



networks:
  webnet:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
